config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
  as :user do
    get ":locale/login" => "devise/sessions#new", :as => :new_user_session
    post ":locale/login" => "devise/sessions#create", :as => :user_session
    get ":locale/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    resources :books, only: :show
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :carts, only: %i(index create destroy) do
      get :reset, on: :collection
    end
    resources :shops, only: %i(show index)
    resources :users, only: %i(new show create) do
      resources :shops, only: %i(new create)
      namespace :shop do
        resources :orders, only: %i(index show) do
          member do 
            put :approve
            put :disclaim
          end
        end
        resource :shops, only: :show
        resources :books do
          collection {post :import}
        end
      end
      resources :orders, only: %i(new create index show) do
        put :cancel, on: :member
      end
    end 
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {pending: 0, success: 1, cancel: 2, disclaim: 3}
  belongs_to :shop
  belongs_to :user
  has_many :order_details, dependent: :destroy
  delegate :name, to: :user, prefix: true
  scope :recent_orders, ->{order created_at: :desc}
  validates :name, :address, :phone, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :books, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, length: {maximum: Settings.length.digit_255}

  def all_books
    books.recent_books
  end

  def all_orders
    orders.recent_orders
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_user
  before_action :load_order, only: %i(cancel show)
  authorize_resource

  def new
    return unless load_book_id_in_cart.empty?

    flash[:danger] = t "order.cart_empty"
    redirect_to root_path
  end

  def create
    add_infor_receiver
    ActiveRecord::Base.transaction do
      list_shop_id_in_cart.each do |shop_id|
        list_book = list_book_by_shop_id shop_id
        order = create_order shop_id
        add_list_book_to_order_detail list_book, order
        update_order_total_price list_book, order
        order.save!
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.failed"
    redirect_to new_user_order_path(current_user)
  else
    reset_cart
    flash[:success] = t "order.success"
    redirect_to root_path
  end

  def index
    @orders = current_user.all_orders.page(params[:page])
                          .per(Settings.length.digit_8)
  end

  def cancel
    if @order.pending?
      @order.cancel!
      flash[:success] = t "order.cancel_success"
    else
      flash[:danger] = t "order.cancel_failed"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.cancel_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  def show
    @order_details = @order.order_details.includes(:book)
    @total = total_order @order_details
  end

  private

  def load_order
    @order = current_user.orders.find_by id: params[:id]
    return if @order

    flash[:danger] = t "order.not_found"
    redirect_to static_pages_home_path
  end

  def create_order shop_id
    current_user.orders.build(
      shop_id: shop_id,
      name: params[:name],
      address: params[:address],
      phone: params[:phone]
    )
  end

  def add_list_book_to_order_detail list_book, order
    list_book.each do |book|
      order.order_details.build(
        quantily: current_cart[book["id"].to_s].to_i,
        price: book["price"].to_i,
        book_id: book["id"].to_i
      )
    end
  end

  def update_order_total_price list_book, order
    total = list_book.map{|b| current_cart[b["id"].to_s].to_i * b["price"].to_i}
    order.total_price = total.inject(0, :+)
  end

  def list_shop_id_in_cart
    Book.by_book_ids(load_book_id_in_cart).pluck(:shop_id).uniq
  end

  def list_book_by_shop_id id
    Book.by_book_ids(load_book_id_in_cart).select{|e| e.shop_id == id}
  end

  def add_infor_receiver
    current_info_receiver[:name] = params[:name]
    current_info_receiver[:address] = params[:address]
    current_info_receiver[:phone] = params[:phone]
  end

  def check_user
    if user_signed_in?
      return if current_user.id == params[:user_id].to_i

      flash[:danger] = t "shared.invalid_permision"
      redirect_to root_url
    else
      flash[:danger] = t "please_login"
      redirect_to login_path
    end
  end
end

app/controllers/shop/books_controller.rb
class Shop::BooksController < ApplicationController
  before_action :check_user, only: %i(index show import)
  before_action :check_file, only: :import
  before_action :load_shop, only: %i(index show)
  before_action :load_book, only: :show
  authorize_resource

  def index
    @books = @shop.all_books
                  .page(params[:page]).per(Settings.length.digit_8)
  end

  def show; end

  def import
    Book.import(@file, current_user.shop.id)
    flash[:success] = t "books.add_success"
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "books.add_fail"
    redirect_to user_shop_books_path(current_user.id)
  else
    redirect_to user_shop_books_path(current_user.id)
  end

  private

  def check_file
    @file = params[:file]
    return @file if CSV.read(@file).count > 1

    flash[:danger] = t "books.require_file"
    redirect_to user_shop_books_path(current_user.id)
  end

  def load_shop
    @shop = current_user.shop
    return if @shop.present?

    flash[:danger] = t("shops.not_found")
    redirect_to root_url
  end

  def load_book
    @book = @shop.books.find_by id: params[:id]
    return if @book

    flash[:danger] = t "books.not_found"
    redirect_to static_pages_home_path
  end

  def check_user
    if user_signed_in?
      return if current_user.id == params[:user_id].to_i

      flash[:danger] = t "shared.invalid_permision"
      redirect_to root_url
    else
      flash[:danger] = t "please_login"
      redirect_to login_path
    end
  end
end

app/controllers/shop/orders_controller.rb
class Shop::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_shop, only: %i(index show approve disclaim)
  before_action :load_order, only: %i(show approve disclaim)
  before_action :check_quantity, only: :approve
  before_action :check_user, only: %i(index show approve disclaim)
  authorize_resource

  def index
    @orders = @shop.all_orders
                   .page(params[:page]).per(Settings.length.digit_10)
  end

  def show
    @order_details = @order.order_details.includes(:book)
    @total = total_order @order_details
  end

  def approve
    ActiveRecord::Base.transaction do
      if @order.pending?
        update_quantity @order
        @order.success!
        flash[:success] = t "order.approve_success"
      else
        flash[:danger] = t "order.approve_failed"
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.approve_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  def disclaim
    if @order.pending?
      @order.disclaim!
      flash[:success] = t "order.disclaim_success"
    else
      flash[:danger] = t "order.disclaim_failed"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.disclaim_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  private

  def update_quantity order
    list_order_detail = order.order_details
    list_order_detail.each do |order_detail|
      book = order_detail.book
      book.quantity -= order_detail.quantily
      book.save!
    end
  end

  def check_quantity
    list_order_detail = @order.order_details
    book_fail = []
    list_order_detail.each do |order_detail|
      if order_detail.book.quantity < order_detail.quantily
        book_fail.push(order_detail.book.id)
      end
    end
    return if book_fail.blank?

    flash[:danger] = t("order.list_book_failed") << book_fail.to_s
    redirect_back(fallback_location: root_path)
  end

  def load_order
    @order = @shop.orders.find_by id: params[:id]
    return if @order

    flash[:danger] = t "order.not_found"
    redirect_to root_url
  end

  def load_shop
    @shop = current_user.shop
    return if @shop.present?

    flash[:danger] = t("shops.not_found")
    redirect_to root_url
  end

  def check_user
    return if current_user.id == params[:user_id].to_i

    flash[:danger] = t "shared.invalid_permision"
    redirect_to root_url
  end
end

app/controllers/shop/shops_controller.rb
class Shop::ShopsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_shop, :check_user, only: :show
  authorize_resource

  def show
    @books = current_user.shop
                         .all_books
                         .page(params[:page]).per(Settings.length.digit_5)
  end

  private

  def load_shop
    @shop = current_user.shop
    return if @shop

    flash[:danger] = t("shops.not_found")
    redirect_to root_url
  end

  def check_user
    if user_signed_in?
      return if current_user.id == params[:user_id].to_i

      flash[:danger] = t "shared.invalid_permision"
      redirect_to root_url
    else
      flash[:danger] = t "please_login"
      redirect_to login_path
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :load_shop, only: :show
  before_action :check_user, only: %i(new create)
  authorize_resource

  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result
               .page(params[:page]).per(Settings.length.digit_6)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.build_shop(shop_params)
    if @shop.save
      flash[:success] = t "shops.success"
      redirect_to user_shop_shops_path(current_user.id)
    else
      flash.now[:danger] = t "shops.fail"
      render :new
    end
  end

  def show
    @books = @shop.all_books
                  .page(params[:page]).per(Settings.length.digit_5)
  end

  private

  def load_shop
    @shop = Shop.find_by id: params[:id]
    return if @shop

    flash[:danger] = t("shops.not_found")
    redirect_to root_url
  end

  def shop_params
    params.require(:shop).permit(:name, :description)
  end

  def check_user
    if user_signed_in?
      return if current_user.id == params[:user_id].to_i

      flash[:danger] = t "shared.invalid_permision"
      redirect_to root_url
    else
      flash[:danger] = t "please_login"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def total_order list_order_detail
    list_order_detail.reduce(0) do |total, order|
      total + order.quantily * order.price
    end
  end
end

app/views/shop/orders/index.html.erb
<% provide :title, @shop.name %>
<div class="body-order">
  <h1 class="body-header list-shop-title text-center"><%=  t "orders.shop_title" %></h1>
  <% if @orders.any? %>
    <div class="row justify-content-center">
      <div class="col-md-10">
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="col-md-1">No.</th>
              <th class="text-center col-md-3"><%= t "orders.customer" %></th>
              <th class="text-center col-md-1"><%= t "orders.phone" %></th>
              <th class="text-center col-md-2"><%= t "orders.total_price" %>
              <th class="text-center col-md-1"><%= t "orders.status" %></th>
              <th class="col-md-4"></th>
            <tr>
          </thead>
          <tbody>
            <% @orders.each_with_index do |order, index|%>
              <tr>
                <td class="align-middle "><%= index +1 %></td>
                <td class="align-middle "><%= order.user_name %></td>
                <td class="text-center align-middle "><%= order.phone %></td>
                <td class="text-center align-middle "><%= number_to_currency(order.total_price,locale: :vi) %></td>
                <td class="text-center align-middle"><div class="badge <%= t "class.#{order.status}" %>"><%= t "orders.#{order.status}" %></div></td>
                <td>
                  <%= link_to t("shared.details"), user_shop_order_path(user_id: current_user.id, id: order.id),
                    class: "btn btn-outline-primary btn-order" %>
                  <% if order.pending? %>
                    <%= link_to t("shared.approve"), approve_user_shop_order_path(current_user, order.id),
                      method: "put", class: "btn btn-outline-success ml-3 mr-3 btn-order" %>
                    <%= link_to t("shared.disclaim"), disclaim_user_shop_order_path(current_user, order),
                      method: "put", class: "btn btn-outline-danger btn-order" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row justify-content-center paginate-white">
      <%= paginate @orders, theme: "twitter-bootstrap-4" %>
    </div>
  <% else %>
    <h2><%= t "orders.not_found" %></h2>
  <% end %>  
</div>

app/views/shop/orders/show.html.erb
<div class="body-order">
  <h1 class="text-center font-tilte"><%=  t "orders.order_info" %></h1>
  <% if @order %>
    <div class=" header-order d-flex justify-content-center">
      <div class="card-header-order row col-md-5">
        <div class="col-md-6">
          <p class="card-order"><b><%= t("orders.customer") %>:</b></p>
          <p class="card-order"><b><%= t("orders.name") %>:</b></p>
          <p class="card-order"><b><%= t("orders.address") %>:</b></p>
          <p class="card-order"><b><%= t("orders.phone") %>:</b></p>
          <p class="card-order"><b><%= t("orders.status") %>:</b></p>
          <p class="card-order"><b><%= t("orders.day_create") %>:</b></p>
        </div>
        <div class="col-md-6 text-center">
          <p class="card-order"><%= @order.user_name %></p>
          <p class="card-order"><%= @order.name %></p>
          <p class="card-order"><%= @order.address %></p>
          <p class="card-order"><%= @order.phone %></p>
          <% if @order.pending? %>
            <p class="card-badges badge badge-warning"><%= t "orders.pending" %></p>
          <% elsif @order.success? %>
            <p class="card-badges badge badge-success"><%= t "orders.success" %></p>
          <% else %>
            <p class="card-badges badge badge-danger "><%= t "orders.cancel" %></p>
          <% end %>
          <p class="card-order"><%= @order.created_at.to_time.strftime("%d/%m/%Y at %l:%M %p") %></p>
        </div>
      </div>
    </div>
    <div class="container contain">
      <div class="row justify-content-center">
        <div class="col-md-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="col-md-1">No.</th>
                <th class="text-center col-md-3"><%= t "orders.details.title" %></th>
                <th class="text-center col-md-1"><%= t "orders.details.quantity" %></th>
                <th class="text-center col-md-2"><%= t "orders.details.price" %>
                <th class="text-center col-md-1"><%= t "orders.details.amount" %></th>
              <tr>
            </thead>
            <tbody>
              <% @order_details.each_with_index do |order_detail, index|%>
                <tr>
                  <td class="align-middle "><%= index +1 %></td>
                  <td class="text-center align-middle "><%= order_detail.book_title %></td>
                  <td class="text-center align-middle "><%= order_detail.quantily %></td>
                  <td class="text-center align-middle "><%= number_to_currency(order_detail.price, locale: :vi) %></td>
                  <td class="text-center align-middle "><%= number_to_currency(order_detail.price*order_detail.quantily, locale: :vi) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <hr>
        <div class="col-md-12 d-flex justify-content-end">
          <div class="col-md-6 d-flex justify-content-end">
            <div class="col-md-3">
              <p class="card-order"><b><%= t "orders.details.total" %></b></p>
            </div>
            <div class="col-md-5">
              <p class="card-order text-right"><b> <%= number_to_currency(@total, locale: :vi) %></b></p>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  <% else %>
    <h2><%= t "orders.not_found" %></h2>
  <% end %>  
</div>