config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
  as :user do
    get ":locale/login" => "devise/sessions#new", :as => :new_user_session
    post ":locale/login" => "devise/sessions#create", :as => :user_session
    get ":locale/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    resources :books, only: :show
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :carts, only: %i(index create destroy) do
      get :reset, on: :collection
    end
    resources :shops, only: %i(show index)
    resources :users, only: %i(new show create) do
      resources :shops, only: %i(new create)
      namespace :shop do
        resources :orders, only: %i(index show) do
          member do 
            put :approve
            put :disclaim
          end
        end
        resource :shops, only: :show
        resources :books do
          collection {post :import}
        end
      end
      resources :orders, only: %i(new create index show) do
        put :cancel, on: :member
      end
    end 
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {pending: 0, success: 1, cancel: 2, disclaim: 3}
  belongs_to :shop
  belongs_to :user
  has_many :order_details, dependent: :destroy
  delegate :name, to: :user, prefix: true
  scope :recent_orders, ->{order created_at: :desc}
  validates :name, :address, :phone, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_user
  before_action :load_order, only: %i(cancel show)
  authorize_resource

  def new
    return unless load_book_id_in_cart.empty?

    flash[:danger] = t "order.cart_empty"
    redirect_to root_path
  end

  def create
    add_infor_receiver
    ActiveRecord::Base.transaction do
      list_shop_id_in_cart.each do |shop_id|
        list_book = list_book_by_shop_id shop_id
        order = create_order shop_id
        add_list_book_to_order_detail list_book, order
        update_order_total_price list_book, order
        order.save!
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.failed"
    redirect_to new_user_order_path(current_user)
  else
    reset_cart
    flash[:success] = t "order.success"
    redirect_to root_path
  end

  def index
    @orders = current_user.all_orders.page(params[:page])
                          .per(Settings.length.digit_8)
  end

  def cancel
    if @order.pending?
      @order.cancel!
      flash[:success] = t "order.cancel_success"
    else
      flash[:danger] = t "order.cancel_failed"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.cancel_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  def show
    @order_details = @order.order_details.includes(:book)
    @total = total_order @order_details
  end

  private

  def load_order
    @order = current_user.orders.find_by id: params[:id]
    return if @order

    flash[:danger] = t "order.not_found"
    redirect_to static_pages_home_path
  end

  def create_order shop_id
    current_user.orders.build(
      shop_id: shop_id,
      name: params[:name],
      address: params[:address],
      phone: params[:phone]
    )
  end

  def add_list_book_to_order_detail list_book, order
    list_book.each do |book|
      order.order_details.build(
        quantily: current_cart[book["id"].to_s].to_i,
        price: book["price"].to_i,
        book_id: book["id"].to_i
      )
    end
  end

  def update_order_total_price list_book, order
    total = list_book.map{|b| current_cart[b["id"].to_s].to_i * b["price"].to_i}
    order.total_price = total.inject(0, :+)
  end

  def list_shop_id_in_cart
    Book.by_book_ids(load_book_id_in_cart).pluck(:shop_id).uniq
  end

  def list_book_by_shop_id id
    Book.by_book_ids(load_book_id_in_cart).select{|e| e.shop_id == id}
  end

  def add_infor_receiver
    current_info_receiver[:name] = params[:name]
    current_info_receiver[:address] = params[:address]
    current_info_receiver[:phone] = params[:phone]
  end

  def check_user
    if user_signed_in?
      return if current_user.id == params[:user_id].to_i

      flash[:danger] = t "shared.invalid_permision"
      redirect_to root_url
    else
      flash[:danger] = t "please_login"
      redirect_to login_path
    end
  end
end

app/controllers/shop/orders_controller.rb
class Shop::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_shop, only: %i(index show approve disclaim)
  before_action :load_order, only: %i(show approve disclaim)
  before_action :check_quantity, only: :approve
  before_action :check_user, only: %i(index show approve disclaim)
  authorize_resource

  def index
    @orders = @shop.all_orders
                   .page(params[:page]).per(Settings.length.digit_10)
  end

  def show
    @order_details = @order.order_details.includes(:book)
    @total = total_order @order_details
  end

  def approve
    ActiveRecord::Base.transaction do
      if @order.pending?
        update_quantity @order
        @order.success!
        flash[:success] = t "order.approve_success"
      else
        flash[:danger] = t "order.approve_failed"
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.approve_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  def disclaim
    if @order.pending?
      @order.disclaim!
      flash[:success] = t "order.disclaim_success"
    else
      flash[:danger] = t "order.disclaim_failed"
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "order.disclaim_failed"
  ensure
    redirect_back(fallback_location: root_path)
  end

  private

  def update_quantity order
    list_order_detail = order.order_details
    list_order_detail.each do |order_detail|
      book = order_detail.book
      book.quantity -= order_detail.quantily
      book.save!
    end
  end

  def check_quantity
    list_order_detail = @order.order_details
    book_fail = []
    list_order_detail.each do |order_detail|
      if order_detail.book.quantity < order_detail.quantily
        book_fail.push(order_detail.book.id)
      end
    end
    return if book_fail.blank?

    flash[:danger] = t("order.list_book_failed") << book_fail.to_s
    redirect_back(fallback_location: root_path)
  end

  def load_order
    @order = @shop.orders.find_by id: params[:id]
    return if @order

    flash[:danger] = t "order.not_found"
    redirect_to root_url
  end

  def load_shop
    @shop = current_user.shop
    return if @shop.present?

    flash[:danger] = t("shops.not_found")
    redirect_to root_url
  end

  def check_user
    return if current_user.id == params[:user_id].to_i

    flash[:danger] = t "shared.invalid_permision"
    redirect_to root_url
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def total_order list_order_detail
    list_order_detail.reduce(0) do |total, order|
      total + order.quantily * order.price
    end
  end
end

app/views/orders/index.html.erb
<% provide :title, t("order.order_infor") %>
<div class="cart-index container user_order_index">
  <% if @orders.any? %>
    <h1 class="text-center cart-index-title">
      <%= t "order.your_orders" %>
    </h1>
    <div class="container">
      <div>
        <table class="table table-hover cart_table">
          <thead>
            <tr>
              <th class="text-center">#</th>
              <th class="text-center"><%= t "order.name" %></th>
              <th class="text-center"><%= t "order.phone" %></th>
              <th class="text-center"><%= t "order.total_price" %></th>
              <th class="text-center"><%= t "order.status" %></th>
              <th class="text-center"></th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each_with_index do |order, index|%>
              <tr>
                <th scope="row" class="text-center"><%= index + 1 %></th>
                <td class="text-center"><%= order.name %></td>
                <td class="text-center"><%= order.phone %></td>
                <td class="text-center">
                  <%= number_to_currency(order.total_price, locale: :vi) %>
                </td>
                <td class="text-center">
                  <span class="badge <%= t "class.#{order.status}" %>">
                    <%= order.status %>
                  </span>
                </td>
                <td class="row">
                  <div class="d-flex flex-column user-btn-detail">
                    <%= link_to t("order.btn_detail"), user_order_path(current_user, order),
                      class: "btn btn-outline-primary" %>
                  </div>
                  <% if order.pending? %>
                    <div class="d-flex flex-column">
                      <%= link_to t("order.btn_cancel"), cancel_user_order_path(current_user, order),
                        method: "put", class: "btn btn-outline-danger" %>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <%= paginate @orders, theme: "twitter-bootstrap-4" %>
    <%= link_to t("cart.back_shopping"),
      static_pages_home_path, class: "btn btn-primary btn-back-shopping-left" %>
  <% else %>
    <h1 class="text-center cart-index-title">
      <%= t "order.no_order" %>
    </h1>
    <%= link_to t("cart.back_shopping"),
      static_pages_home_path, class: "btn btn-primary btn-back-shopping" %>
  <% end %>
</div>

app/views/orders/new.html.erb
<% provide :title, t("order.title") %>
<div class="container delivery-info">
  <h1 class="text-center cart-index-title">
    <%= t "order.title" %>
  </h1>
  <%= form_tag user_orders_path do %>
    <div class="delivery-name">
      <h4><%= t "order.name" %></h4>
      <div class="form-group quantity">
          <%= text_field_tag :name, load_param_name, class: "form-control",
          required: "required" %>
      </div>
    </div>
    <div class="delivery-name">
      <h4><%= t "order.address" %></h4>
      <div class="form-group quantity">
        <%= text_field_tag :address, current_info_receiver["address"], class: "form-control",
          required: "required" %>
      </div>
    </div>
    <div class="delivery-name">
      <h4><%= t "order.phone" %></h4>
      <div class="form-group quantity">
        <%= text_field_tag :phone, current_info_receiver["phone"], class: "form-control",
          required: "required" %>
      </div>
    </div>
    <div>
      <%= submit_tag t("order.btn_pay"), class: "btn btn-info delivery-btn" %>
    </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="body-order">
  <h1 class="text-center font-tilte"><%=  t "orders.order_info" %></h1>
  <% if @order %>
    <div class=" header-order d-flex justify-content-center">
      <div class="card-header-order row col-md-5">
        <div class="col-md-6">
          <p class="card-order"><b><%= t("orders.customer") %>:</b></p>
          <p class="card-order"><b><%= t("orders.name") %>:</b></p>
          <p class="card-order"><b><%= t("orders.address") %>:</b></p>
          <p class="card-order"><b><%= t("orders.phone") %>:</b></p>
          <p class="card-order"><b><%= t("orders.status") %>:</b></p>
          <p class="card-order"><b><%= t("orders.day_create") %>:</b></p>
        </div>
        <div class="col-md-6 text-center">
          <p class="card-order"><%= @order.user_name %></p>
          <p class="card-order"><%= @order.name %></p>
          <p class="card-order"><%= @order.address %></p>
          <p class="card-order"><%= @order.phone %></p>
          <p class="card-order">
            <span class="badge <%= t "class.#{@order.status}" %>">
              <%= @order.status %>
            </span>
          </p>
          <p class="card-order"><%= @order.created_at.to_time.strftime("%d/%m/%Y at %l:%M %p") %></p>
        </div>
      </div>
    </div>
    <div class="container contain">
      <div class="row justify-content-center">
        <div class="col-md-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="col-md-1">No.</th>
                <th class="text-center col-md-3"><%= t "orders.details.title" %></th>
                <th class="text-center col-md-1"><%= t "orders.details.quantity" %></th>
                <th class="text-center col-md-2"><%= t "orders.details.price" %>
                  <th class="text-center col-md-1"><%= t "orders.details.amount" %></th>
                  <tr>
                  </thead>
                  <tbody>
                    <% @order_details.each_with_index do |order_detail, index|%>
                      <tr>
                        <td class="align-middle "><%= index +1 %></td>
                        <td class="text-center align-middle "><%= order_detail.book_title %></td>
                        <td class="text-center align-middle "><%= order_detail.quantily %></td>
                        <td class="text-center align-middle "><%= number_to_currency(order_detail.price, locale: :vi) %></td>
                        <td class="text-center align-middle "><%= number_to_currency(order_detail.price*order_detail.quantily, locale: :vi) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <hr>
              <div class="col-md-12 d-flex justify-content-end">
                <div class="col-md-6 d-flex justify-content-end">
                  <div class="col-md-3">
                    <p class="card-order"><b><%= t "orders.details.total" %></b></p>
                  </div>
                  <div class="col-md-5">
                    <p class="card-order text-right"><b> <%= number_to_currency(@total, locale: :vi) %></b></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <h2><%= t "orders.not_found" %></h2>
        <% end %>
      </div>