config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
  as :user do
    get ":locale/login" => "devise/sessions#new", :as => :new_user_session
    post ":locale/login" => "devise/sessions#create", :as => :user_session
    get ":locale/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    resources :books, only: :show
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :carts, only: %i(index create destroy) do
      get :reset, on: :collection
    end
    resources :shops, only: %i(show index)
    resources :users, only: %i(new show create) do
      resources :shops, only: %i(new create)
      namespace :shop do
        resources :orders, only: %i(index show) do
          member do 
            put :approve
            put :disclaim
          end
        end
        resource :shops, only: :show
        resources :books do
          collection {post :import}
        end
      end
      resources :orders, only: %i(new create index show) do
        put :cancel, on: :member
      end
    end 
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_book, only: :create

  def index
    @books = Book.by_book_ids(load_book_id_in_cart)
    @cart = current_cart
    store_location
  end

  def create
    add_book_to_cart(params[:book_id], params[:quantity]) if check_quantity
    respond_to do |format|
      format.js
    end
  end

  def destroy
    delete_cart_item params[:id]
    redirect_to carts_path
  end

  def reset
    reset_cart
    redirect_to carts_path
  end

  private

  def check_quantity
    @quantity = @book.quantity >= params[:quantity].to_i
  end

  def load_book
    @book = Book.find_by id: params[:book_id]
    return if @book

    flash[:danger] = t "books.not_found"
    redirect_to static_pages_home_path
  end
end

app/views/carts/create.html.erb
<% if @quantity == false %>
  $('#alert_add_cart').html('<%= j render "shared/alert_add_cart_failed" %>');
<% else %>
  $('#cart').html('<%= j render "shared/cart" %>');
  $('#alert_add_cart').html('<%= j render "shared/alert_add_cart_success" %>');
<% end %>

app/views/carts/index.html.erb
<% provide :title, t("cart.cart")%>
<div class="cart-index container">
  <% if @books.any? %>
    <h1 class="text-center cart-index-title">
      <%= t "cart.book_in_cart" %>
    </h1>
    <div class="container">
      <div class="row">
        <table class="table table-hover cart_table">
          <thead>
            <tr>
              <th>#</th>
              <th><%= t "cart.title" %></th>
              <th></th>
              <th><%= t "cart.quantity" %></th>
              <th><%= t "cart.total" %></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each_with_index do |book, index|%>
              <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= book.title %></td>
                <td><%= image_tag("bucbuc_logo.png", alt: "book")%></td>
                <td><%= @cart[book.id.to_s] %></td>
                <td>
                  <%= number_to_currency(book.price * @cart[book.id.to_s].to_f,
                  locale: :vi) %></td>
                <td>
                  <div class="d-flex flex-column">
                    <%= link_to t("cart.delete"), cart_path(book.id),
                      method: "delete", class: "btn btn-outline-danger" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <% if user_signed_in? %>
        <%= link_to t("cart.pay"), new_user_order_path(current_user),
          class: "btn btn-primary btn-pay" %>
      <% else %>
        <%= link_to t("cart.login_pay"), login_path,
          class: "btn btn-primary btn-pay" %>
      <% end %>
      <%= link_to t("cart.reset"), reset_carts_path,
        class: "btn btn-danger btn-pay" %>
    </div>
    <%= link_to t("cart.back_shopping"),
      static_pages_home_path, class: "btn btn-primary btn-back-shopping-left" %>
  <% else %>
    <h1 class="text-center cart-index-title">
      <%= t "cart.no_book" %>
    </h1>
    <%= link_to t("cart.back_shopping"),
      static_pages_home_path, class: "btn btn-primary btn-back-shopping" %>
  <% end %>
</div>