config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
  as :user do
    get ":locale/login" => "devise/sessions#new", :as => :new_user_session
    post ":locale/login" => "devise/sessions#create", :as => :user_session
    get ":locale/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    resources :books, only: :show
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :carts, only: %i(index create destroy) do
      get :reset, on: :collection
    end
    resources :shops, only: %i(show index)
    resources :users, only: %i(new show create) do
      resources :shops, only: %i(new create)
      namespace :shop do
        resources :orders, only: %i(index show) do
          member do 
            put :approve
            put :disclaim
          end
        end
        resource :shops, only: :show
        resources :books do
          collection {post :import}
        end
      end
      resources :orders, only: %i(new create index show) do
        put :cancel, on: :member
      end
    end 
  end
end

app/views/layouts/_footer.html.erb
<nav class="navbar footer">
  <p class="navbar-brand">© <%= t "footer" %></p>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to image_tag("bucbuc_logo.png", alt: "logo"), static_pages_home_path,id: "logo_img" %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to t("nav.home"), static_pages_home_path, class: "nav-link" %></li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <% if current_user.shop.present? %>
            <%= link_to t("nav.your_shop"),  user_shop_shops_path(current_user.id),
              class: "nav-link" %>
          <% else %>
            <%= link_to t("nav.create_shop"), new_user_shop_path(current_user.id),
              class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item"><%= link_to t("nav.transactions"), user_orders_path(current_user),
          class: "nav-link" %></li>
      <% end %>
      <li class="nav-item"><%= link_to t("nav.members"), shops_path, class: "nav-link" %></li>
    </ul>
    <ul class="navbar-nav justify-content-right">
      <% unless user_signed_in? %>
        <li class="nav-item"><%= link_to t("nav.login_signup"), new_user_session_path, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to t("nav.logout"), destroy_user_session_path, class: "nav-link" %></li>
      <% end %>
      <li class="dropdown">
        <%= link_to "#", class: "dropdown-toggle nav-link", data: {toggle: "dropdown"} do %>
          <%= t "nav.language.language" %>
          <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to t("nav.language.en"), locale:"en", class: "dropdown-item" %></li>
          <li><%= link_to t("nav.language.vie"), locale:"vi", class: "dropdown-item" %></li>
        </ul>
      </li>
      <li id="cart">
        <%= render "shared/cart" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container flash-noti">
      <% flash.each do |message_type, message| %>
        <% if message_type == "notice" %>
          <div class="alert alert-success"><%= message %></div>
        <% elsif message_type == "alert" %>
          <div class="alert alert-danger"><%= message %></div>
        <% else %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <% end %>
    </div>
    <div id="alert_add_cart"></div>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>